#!/usr/bin/env node

// Supabase project migration script: OLD → NEW
// Copies all mainnet table data (no _sepolia tables)
// Run with: node temp_migrate.mjs

const OLD_URL = 'https://hzpwkpjxhtpcygrwtwku.supabase.co';
const OLD_KEY = 'REDACTED_SUPABASE_SERVICE_ROLE';

const NEW_URL = 'https://kfnprbhoodmgfhqojmqp.supabase.co';
const NEW_KEY = 'REDACTED_SUPABASE_SERVICE_ROLE';

const BATCH_SIZE = 1000;

// ─── SQL Schema ───
// Uses GENERATED BY DEFAULT (not ALWAYS) so we can insert explicit identity values via REST API

const SCHEMA_SQL = `
-- ============================================================
-- SCHEMA FOR NEW SUPABASE PROJECT
-- Run this in the SQL Editor of the NEW project BEFORE running this script
-- ============================================================

-- Sequences
CREATE SEQUENCE IF NOT EXISTS attributes_new_id_seq;
CREATE SEQUENCE IF NOT EXISTS lottery_wins_id_seq;

-- 1. collections (no FK deps)
CREATE TABLE IF NOT EXISTS public.collections (
  slug text NOT NULL,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "posterHashId" text,
  name text NOT NULL,
  description text,
  image text,
  "singleName" text,
  active boolean NOT NULL DEFAULT false,
  supply bigint NOT NULL DEFAULT '0'::bigint,
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
  website text,
  twitter text,
  discord text,
  "isMinting" boolean NOT NULL DEFAULT false,
  "hasBackgrounds" boolean NOT NULL DEFAULT false,
  notifications boolean NOT NULL DEFAULT false,
  "mintEnabled" boolean NOT NULL DEFAULT false,
  "defaultBackground" text,
  standalone boolean NOT NULL DEFAULT false,
  "shortName" text,
  CONSTRAINT collections_pkey PRIMARY KEY (slug)
);

-- 2. ethscriptions (FK -> collections)
CREATE TABLE IF NOT EXISTS public.ethscriptions (
  "createdAt" timestamp with time zone DEFAULT now(),
  creator text,
  owner text,
  "hashId" text NOT NULL UNIQUE,
  sha text NOT NULL UNIQUE,
  "tokenId" bigint NOT NULL DEFAULT '-1'::bigint,
  "prevOwner" text,
  slug text,
  "oldHashId" text UNIQUE,
  locked boolean NOT NULL DEFAULT false,
  CONSTRAINT ethscriptions_pkey PRIMARY KEY ("hashId"),
  CONSTRAINT ethscriptions_slug_fkey FOREIGN KEY (slug) REFERENCES public.collections(slug)
);

-- 3. _global_config (FK -> collections)
CREATE TABLE IF NOT EXISTS public._global_config (
  maintenance boolean NOT NULL DEFAULT false,
  network bigint NOT NULL DEFAULT '1'::bigint,
  chat boolean NOT NULL DEFAULT true,
  comments boolean NOT NULL DEFAULT false,
  "defaultCollection" text NOT NULL DEFAULT 'ethereum-phunks'::text,
  CONSTRAINT _global_config_pkey PRIMARY KEY (network),
  CONSTRAINT "_global_config_defaultCollection_fkey" FOREIGN KEY ("defaultCollection") REFERENCES public.collections(slug)
);

-- 4. attributes_new (no FK)
CREATE TABLE IF NOT EXISTS public.attributes_new (
  id bigint NOT NULL DEFAULT nextval('attributes_new_id_seq'::regclass),
  sha text NOT NULL,
  "values" jsonb NOT NULL,
  slug text NOT NULL,
  "tokenId" integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attributes_new_pkey PRIMARY KEY (id)
);

-- 5. events (FK -> ethscriptions)
CREATE TABLE IF NOT EXISTS public.events (
  "hashId" text NOT NULL,
  "from" text NOT NULL,
  "to" text NOT NULL,
  "blockHash" text NOT NULL,
  "txHash" text NOT NULL,
  "blockNumber" bigint,
  "blockTimestamp" timestamp with time zone DEFAULT now(),
  type text,
  value text,
  "txId" text NOT NULL UNIQUE,
  "txIndex" bigint NOT NULL DEFAULT '-1'::bigint,
  CONSTRAINT events_pkey PRIMARY KEY ("txId"),
  CONSTRAINT "events_hashId_fkey" FOREIGN KEY ("hashId") REFERENCES public.ethscriptions("hashId")
);

-- 6. listings (FK -> ethscriptions)
CREATE TABLE IF NOT EXISTS public.listings (
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "hashId" text NOT NULL,
  listed boolean NOT NULL DEFAULT false,
  "toAddress" text,
  "minValue" text NOT NULL,
  "listedBy" text NOT NULL,
  "txHash" text NOT NULL,
  l2 boolean NOT NULL DEFAULT false,
  CONSTRAINT listings_pkey PRIMARY KEY ("hashId"),
  CONSTRAINT "listings_hashId_fkey" FOREIGN KEY ("hashId") REFERENCES public.ethscriptions("hashId")
);

-- 7. bids (FK -> ethscriptions)
CREATE TABLE IF NOT EXISTS public.bids (
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "hashId" text NOT NULL,
  "fromAddress" text NOT NULL,
  value text NOT NULL DEFAULT '0'::text,
  "txHash" text NOT NULL,
  CONSTRAINT bids_pkey PRIMARY KEY ("hashId"),
  CONSTRAINT "bids_hashId_fkey" FOREIGN KEY ("hashId") REFERENCES public.ethscriptions("hashId")
);

-- 8. auctions (FK -> ethscriptions)
CREATE TABLE IF NOT EXISTS public.auctions (
  "auctionId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "hashId" text NOT NULL,
  "prevOwner" text,
  amount text NOT NULL DEFAULT '0'::text,
  "startTime" timestamp with time zone,
  "endTime" timestamp with time zone,
  bidder text,
  settled boolean NOT NULL DEFAULT false,
  CONSTRAINT auctions_pkey PRIMARY KEY ("auctionId"),
  CONSTRAINT "auctions_hashId_fkey" FOREIGN KEY ("hashId") REFERENCES public.ethscriptions("hashId")
);

-- 9. auctionBids (FK -> auctions)
CREATE TABLE IF NOT EXISTS public."auctionBids" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "auctionId" bigint NOT NULL,
  "fromAddress" text NOT NULL DEFAULT ''::text,
  amount text NOT NULL DEFAULT '0'::text,
  extended boolean NOT NULL DEFAULT false,
  CONSTRAINT "auctionBids_pkey" PRIMARY KEY (id),
  CONSTRAINT "auctionBids_auctionId_fkey" FOREIGN KEY ("auctionId") REFERENCES public.auctions("auctionId")
);

-- 10. comments (no FK)
CREATE TABLE IF NOT EXISTS public.comments (
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  content text,
  topic text NOT NULL,
  version text NOT NULL DEFAULT '0.0.1'::text,
  encoding text NOT NULL,
  "topicType" text,
  id text NOT NULL,
  "from" text,
  deleted boolean NOT NULL DEFAULT false,
  type text NOT NULL DEFAULT 'comment'::text,
  CONSTRAINT comments_pkey PRIMARY KEY (id)
);

-- 11. users (no FK)
CREATE TABLE IF NOT EXISTS public.users (
  "createdAt" timestamp with time zone DEFAULT now(),
  address text NOT NULL,
  points bigint NOT NULL DEFAULT '0'::bigint,
  CONSTRAINT users_pkey PRIMARY KEY (address)
);

-- 12. blocks (no FK)
CREATE TABLE IF NOT EXISTS public.blocks (
  network bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "blockNumber" bigint NOT NULL DEFAULT '0'::bigint,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT blocks_pkey PRIMARY KEY (network)
);

-- 13. lottery_wins (no FK)
CREATE TABLE IF NOT EXISTS public.lottery_wins (
  id integer NOT NULL DEFAULT nextval('lottery_wins_id_seq'::regclass),
  play_id integer,
  winner text NOT NULL,
  hash_id text,
  sha text,
  token_id integer,
  collection_slug text,
  transfer_status text DEFAULT 'transferred'::text,
  tx_hash text,
  created_at timestamp with time zone DEFAULT now(),
  contract_address text NOT NULL DEFAULT ''::text,
  CONSTRAINT lottery_wins_pkey PRIMARY KEY (id)
);

-- 14. nfts (FK -> ethscriptions)
CREATE TABLE IF NOT EXISTS public.nfts (
  "tokenId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
  "hashId" text NOT NULL,
  owner text,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT nfts_pkey PRIMARY KEY ("tokenId", "hashId"),
  CONSTRAINT "nfts_hashId_fkey" FOREIGN KEY ("hashId") REFERENCES public.ethscriptions("hashId")
);

-- 15. connected_accounts (no FK)
CREATE TABLE IF NOT EXISTS public.connected_accounts (
  id text NOT NULL,
  "publicKeys" jsonb,
  CONSTRAINT connected_accounts_pkey PRIMARY KEY (id)
);

-- 16. verifier_servers (no FK)
CREATE TABLE IF NOT EXISTS public.verifier_servers (
  id text NOT NULL,
  name text NOT NULL,
  role_id text,
  CONSTRAINT verifier_servers_pkey PRIMARY KEY (id)
);

-- 17. verifier_users (no FK)
CREATE TABLE IF NOT EXISTS public.verifier_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id text NOT NULL UNIQUE,
  servers jsonb NOT NULL DEFAULT '{}'::jsonb,
  address text NOT NULL UNIQUE,
  CONSTRAINT verifier_users_pkey PRIMARY KEY (id, user_id)
);
`;

// ─── Table migration order (FK-safe) ───

const TABLES = [
  // Tier 0: no FK deps
  { name: 'collections', orderBy: 'slug' },
  // Tier 1: FK -> collections
  { name: 'ethscriptions', orderBy: 'hashId' },
  { name: '_global_config', orderBy: 'network' },
  // Tier 2: FK -> ethscriptions
  { name: 'events', orderBy: 'txId' },
  { name: 'listings', orderBy: 'hashId' },
  { name: 'bids', orderBy: 'hashId' },
  { name: 'auctions', orderBy: 'auctionId' },
  { name: 'nfts', orderBy: 'tokenId' },
  // Tier 3: FK -> auctions
  { name: 'auctionBids', orderBy: 'id' },
  // No FK deps
  { name: 'attributes_new', orderBy: 'id' },
  { name: 'comments', orderBy: 'id' },
  { name: 'users', orderBy: 'address' },
  { name: 'blocks', orderBy: 'network' },
  { name: 'lottery_wins', orderBy: 'id' },
  { name: 'connected_accounts', orderBy: 'id' },
  { name: 'verifier_servers', orderBy: 'id' },
  { name: 'verifier_users', orderBy: 'id' },
];

// ─── Helpers ───

function restUrl(baseUrl, table) {
  return `${baseUrl}/rest/v1/${table}`;
}

function hdrs(apiKey, extra = {}) {
  return {
    'apikey': apiKey,
    'Authorization': `Bearer ${apiKey}`,
    'Content-Type': 'application/json',
    ...extra,
  };
}

async function fetchAllRows(baseUrl, apiKey, tableName, orderBy) {
  const allRows = [];
  let offset = 0;

  while (true) {
    const url = `${restUrl(baseUrl, tableName)}?select=*&order=${orderBy}.asc&limit=${BATCH_SIZE}&offset=${offset}`;
    const res = await fetch(url, {
      headers: hdrs(apiKey, { 'Prefer': 'count=exact' }),
    });

    if (!res.ok) {
      const body = await res.text();
      throw new Error(`Failed to fetch ${tableName} at offset ${offset}: ${res.status} ${body}`);
    }

    const data = await res.json();
    if (data.length === 0) break;

    allRows.push(...data);
    offset += data.length;

    const contentRange = res.headers.get('content-range');
    const total = contentRange ? contentRange.split('/')[1] : '?';
    process.stdout.write(`  Reading ${tableName}: ${allRows.length}/${total} rows\r`);

    if (data.length < BATCH_SIZE) break;
  }

  console.log(`  Read ${tableName}: ${allRows.length} rows total                    `);
  return allRows;
}

async function insertRows(baseUrl, apiKey, tableName, rows) {
  if (rows.length === 0) {
    console.log(`  ${tableName}: 0 rows, skipping insert`);
    return;
  }

  let inserted = 0;

  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);

    const res = await fetch(restUrl(baseUrl, tableName), {
      method: 'POST',
      headers: hdrs(apiKey, { 'Prefer': 'return=minimal' }),
      body: JSON.stringify(batch),
    });

    if (!res.ok) {
      const body = await res.text();
      // If we get a conflict (duplicates), try upsert
      if (res.status === 409) {
        console.warn(`\n  Got 409 conflict on ${tableName}, trying upsert...`);
        const res2 = await fetch(restUrl(baseUrl, tableName), {
          method: 'POST',
          headers: hdrs(apiKey, {
            'Prefer': 'return=minimal,resolution=merge-duplicates',
          }),
          body: JSON.stringify(batch),
        });
        if (!res2.ok) {
          const body2 = await res2.text();
          throw new Error(`Upsert failed for ${tableName} batch at ${i}: ${res2.status} ${body2}`);
        }
      } else {
        throw new Error(`Insert failed for ${tableName} batch at ${i}: ${res.status} ${body}`);
      }
    }

    inserted += batch.length;
    process.stdout.write(`  Inserting ${tableName}: ${inserted}/${rows.length}\r`);
  }

  console.log(`  Inserted ${tableName}: ${inserted} rows                    `);
}

// ─── Main ───

async function main() {
  console.log('='.repeat(70));
  console.log('SUPABASE PROJECT MIGRATION');
  console.log('='.repeat(70));
  console.log(`\nOLD: ${OLD_URL}`);
  console.log(`NEW: ${NEW_URL}\n`);

  // Print schema SQL
  console.log('-'.repeat(70));
  console.log('SQL SCHEMA - Run in NEW project SQL Editor BEFORE data migration:');
  console.log('-'.repeat(70));
  console.log(SCHEMA_SQL);
  console.log('-'.repeat(70));

  // Verify connectivity to both projects
  console.log('\nVerifying connectivity...');

  const oldCheck = await fetch(`${restUrl(OLD_URL, 'collections')}?select=slug&limit=1`, {
    headers: hdrs(OLD_KEY),
  });
  if (!oldCheck.ok) {
    throw new Error(`Cannot connect to OLD project: ${oldCheck.status} ${await oldCheck.text()}`);
  }
  console.log('  OLD project: OK');

  const newCheck = await fetch(`${restUrl(NEW_URL, 'collections')}?select=slug&limit=1`, {
    headers: hdrs(NEW_KEY),
  });
  if (!newCheck.ok) {
    const errText = await newCheck.text();
    console.error(`\n  Cannot connect to NEW project or tables not created yet.`);
    console.error(`  Status: ${newCheck.status}`);
    console.error(`  Error: ${errText}`);
    console.error(`\n  Please run the SQL schema above in the NEW project's SQL Editor first.`);
    process.exit(1);
  }
  console.log('  NEW project: OK');

  console.log('\nStarting data migration...\n');

  const sequenceResets = [];

  for (const table of TABLES) {
    console.log(`\n${'='.repeat(50)}`);
    console.log(`Migrating: ${table.name}`);
    console.log('='.repeat(50));

    try {
      // Read all rows from OLD project
      const rows = await fetchAllRows(OLD_URL, OLD_KEY, table.name, table.orderBy);

      if (rows.length === 0) {
        console.log(`  ${table.name}: empty, nothing to migrate`);
        continue;
      }

      // Insert into NEW project
      await insertRows(NEW_URL, NEW_KEY, table.name, rows);

    } catch (err) {
      console.error(`\n  ERROR migrating ${table.name}: ${err.message}`);
      console.error(`  Continuing with next table...\n`);
    }
  }

  // Print post-migration SQL
  console.log('\n' + '='.repeat(70));
  console.log('POST-MIGRATION: Run this SQL in the NEW project to reset sequences:');
  console.log('='.repeat(70));
  console.log(`
-- Reset all identity/serial sequences to match imported data:
SELECT setval(pg_get_serial_sequence('collections', 'id'), COALESCE((SELECT MAX(id) FROM collections), 1));
SELECT setval(pg_get_serial_sequence('auctions', 'auctionId'), COALESCE((SELECT MAX("auctionId") FROM auctions), 1));
SELECT setval(pg_get_serial_sequence('"auctionBids"', 'id'), COALESCE((SELECT MAX(id) FROM "auctionBids"), 1));
SELECT setval(pg_get_serial_sequence('blocks', 'network'), COALESCE((SELECT MAX(network) FROM blocks), 1));
SELECT setval(pg_get_serial_sequence('nfts', 'tokenId'), COALESCE((SELECT MAX("tokenId") FROM nfts), 1));
SELECT setval(pg_get_serial_sequence('verifier_users', 'id'), COALESCE((SELECT MAX(id) FROM verifier_users), 1));
SELECT setval('attributes_new_id_seq', COALESCE((SELECT MAX(id) FROM attributes_new), 1));
SELECT setval('lottery_wins_id_seq', COALESCE((SELECT MAX(id) FROM lottery_wins), 1));
`);

  console.log('='.repeat(70));
  console.log('MIGRATION COMPLETE');
  console.log('='.repeat(70));
  console.log('\nNext steps:');
  console.log('1. Run the sequence reset SQL above in the NEW project SQL Editor');
  console.log('2. Verify row counts match between OLD and NEW');
  console.log('3. Migrate storage buckets separately');
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
