import { Inject, Injectable, signal } from '@angular/core';
import { DOCUMENT } from '@angular/common';

export type MenuLanguage = 'en' | 'es' | 'ja' | 'zh';
export type MenuFont = 'default' | 'blockscript' | 'high-blockscript';

@Injectable({
  providedIn: 'root',
})
export class PhunkPreferencesService {
  currentLanguage = signal<MenuLanguage>(this.loadLanguage());
  currentFont = signal<MenuFont>(this.loadFont());

  languageOptions: { value: MenuLanguage; flag: string; labelKey: string; nativeLabel: string }[] = [
    { value: 'en', flag: 'assets/flags/us.svg', labelKey: 'english', nativeLabel: 'English' },
    { value: 'es', flag: 'assets/flags/mx.svg', labelKey: 'spanish', nativeLabel: 'Español' },
    { value: 'ja', flag: 'assets/flags/jp.svg', labelKey: 'japanese', nativeLabel: '日本語' },
    { value: 'zh', flag: 'assets/flags/cn.svg', labelKey: 'chinese', nativeLabel: '中文' },
  ];

  fontOptions: { value: MenuFont; labelKey: string; className: string; sample: string }[] = [
    { value: 'default', labelKey: 'defaultFont', className: 'sample-default', sample: 'Aa' },
    { value: 'blockscript', labelKey: 'blockscriptFont', className: 'sample-blockscript', sample: 'A' },
    { value: 'high-blockscript', labelKey: 'highBlockscriptFont', className: 'sample-high-blockscript', sample: 'A' },
  ];

  private translations: Record<MenuLanguage, Record<string, string>> = {
    en: {
      withdrawFunds: 'Withdraw Funds',
      disconnect: 'Disconnect',
      fartLeaderboard: 'Fart Leaderboard',
      fartLeaderboardDescription: 'Farts represent your buying activity within the ecosystem. Earn farts by purchasing items across the marketplace, auction, and lottery.',
      farts: 'Farts',
      wallet: 'Wallet',
      buys: 'Buys',
      noResultsFound: 'No results found.',
      topFartHolder: '#1 Fart holder',
      curatedCollections: 'Curated Collections',
      philipLottery: 'Philip Lottery V67',
      pro: 'Pro',
      auctionHouse: 'Auction House',
      phunkquidity: 'Phunkquidity',
      phunkSwap: 'Phunk Swap',
      allOwners: 'All Owners',
      dystolabz: 'DystoLabz',
      adminPanel: 'Admin Panel',
      yourActivity: 'Your Activity',
      noRecentActivity: 'No recent activity.',
      back: 'Back',
      active: 'Active',
      listings: 'Listings',
      languageAndFontControls: 'Language and font controls',
      english: 'English',
      spanish: 'Spanish',
      japanese: 'Japanese',
      chinese: 'Chinese',
      defaultFont: 'Default font',
      blockscriptFont: 'Blockscript font',
      highBlockscriptFont: 'High Blockscript font',
      leaderboardImageAlt: 'QuantumPhunk 9986',
      recentActivity: 'Recent Activity',
      all: 'All',
      offered: 'Offered',
      sold: 'Sold',
      transferred: 'Transferred',
      created: 'Created',
      won: 'Won',
      auction: 'Auction',
      bid: 'bid',
      mutated: 'Mutated',
      devolved: 'Devolved',
      bought: 'Bought',
      for: 'for',
      of: 'of',
      by: 'by',
      inLotteryBy: 'in lottery by',
      auctionWonBy: 'Auction won by',
      auctionEndedNoBids: 'Auction ended - no bids',
      auctionBidOf: 'Auction bid of',
      newBidOf: 'New bid of',
      bidWithdrawn: 'Bid withdrawn',
      offeredFor: 'Offered for',
      transferredTo: 'Transferred to',
      bridgedLockedBy: 'Bridged (Locked) by',
      bridgedUnlockedBy: 'Bridged (Unlocked) by',
      escrowedBy: 'Escrowed by',
      mutatedBy: 'Mutated by',
      devolvedBy: 'Devolved by',
      onAuction: 'On Auction',
      viewMore: 'View More',
      bids: 'Bids',
      reserve: 'Reserve',
      winning: 'Winning',
      current: 'Current',
      timeRemaining: 'Time remaining',
      settled: 'Settled',
      connectAuction: 'Connect your wallet to interact with this auction',
      waitingAuction: 'Waiting for the first auction to start',
      auctionClosed: 'This auction is now closed',
      settling: 'Settling...',
      settle: 'Settle',
      pending: 'Pending...',
      placeBid: 'Place Bid',
      txPending: 'Your transaction is pending.',
      viewOnEtherscan: 'View it on etherscan',
      bidHistory: 'Bid history',
      noBids: 'This auction has no bids',
      viewAll: 'View all',
      connect: 'Connect',
      pointsMultiplier: 'farts multiplier',
      badInputTryAgain: 'Bad input. Try again',
      searchPlaceholder: 'Search: 0x, ens or Ethscription ID',
      searchHistory: 'Search History',
      clear: 'clear',
      close: 'close',
      go: 'Go',
      from: 'from',
      viewMessage: 'View message',
      version: 'Version',
      marketplace: 'Marketplace',
      points: 'Farts',
      lottery: 'Lottery',
      lottery2: 'Lottery 2',
      mutation: 'Mutation',
      riskDisclaimer: 'By using this app, you accept all risks associated, including the loss of funds. The creators of QuantumPhunks are not liable for any issues or damages that may arise from its use.',
      bePhunky: 'Be Phree. Be Phunky. 👍',
      marketStatus: 'Market Status',
      provenanceHash: 'Provenance Hash',
      buy: 'Buy',
      sell: 'Sell',
      sendToEscrow: 'Send to escrow',
      withdrawFromEscrow: 'Withdraw from escrow',
      delist: 'Delist',
      transfer: 'Transfer',
      connectItem: 'Connect an Ethereum wallet to interact with this item',
      attributes: 'Attributes',
      attribute: 'Attribute',
      loading: 'Loading...',
      transferToAddress: 'Transfer to address',
      cancel: 'Cancel',
      submit: 'Submit',
      askingPrice: 'Asking Price',
      listPrivately: 'List Privately',
      offerToAddress: 'Offer to Address',
      offer: 'Offer',
      escrowSaleNotice: 'Offering your item for sale will send it to our contract to be held in escrow. You can withdraw it at any time.',
      royaltyNotice: 'A 5% royalty applies on every sale.',
      sendToEscrowCaps: 'Send to Escrow',
      auctionHistory: 'Auction history',
      currentBlock: 'Current',
      indexer: 'Indexer',
      synced: 'synced',
      blocksBehind: 'blocks behind',
      indexerLogs: 'Indexer Logs',
      initializingLogs: 'Initializing logs',
      connectedWaitingLogs: 'Connected - waiting for logs',
      loaded: 'loaded',
      openingLiveFeed: 'Opening live indexer feed...',
      waitingNextLog: 'Connected. Waiting for the next log entry.',
      noSettledAuctions: 'No auctions have been settled yet',
      connectWallet: 'Connect Wallet',
      detected: 'Detected',
      owned: 'Owned',
      forSale: 'For Sale',
      showingOwned: 'Showing owned',
      showingLowestOffers: 'Showing lowest price offers',
      viewAllLower: 'view all',
      lowestPricePrefix: 'The lowest price',
      currentlyForSaleIs: 'currently for sale is',
      viewAllCollectionPrefix: 'View all',
      secondsAgo: 's ago',
      minutesAgo: 'm ago',
      hoursAgo: 'h ago',
      daysAgo: 'd ago',
      overallStats: 'Overall Stats',
      totalArtifacts: 'Total Artifacts',
      uniqueTraitValues: 'Unique Trait Values',
      uniqueTraitTypes: 'Unique Trait Types',
      totalOneOfOnes: 'Total One of Ones',
      owners: 'Owners',
      allTypesAndAttributes: 'All %type% Types and Attributes',
      rock: 'Rock',
      phunk: 'Phunk',
      showing: 'Showing',
      sort: 'Sort',
      filterByAttribute: 'Filter by Attribute',
      select: 'Select',
      selected: 'selected',
      list: 'List',
      withdraw: 'Withdraw',
      totalCost: 'Total cost',
      buySelected: 'Buy Selected',
      comments: 'Comments',
      leaveComment: 'Leave a comment...',
      addComment: 'Add comment',
      noComments: 'No comments.',
      reply: 'reply',
      replies: 'replies',
      delete: 'delete',
      clearFilters: 'Clear Filters',
      typesAndAttributes: 'Types and Attributes',
      fullCollection: 'Full Collection',
      on: 'ON',
      off: 'OFF',
      attributeCount: 'Attribute Count',
      numberOfAttributes: '# of Attributes',
      rarity: 'Rarity',
      examples: 'Examples',
      value: 'value',
      values: 'values',
      oneOfOne: 'One of One',
      common: 'Common',
      uncommon: 'Uncommon',
      rare: 'Rare',
      elite: 'Elite',
      epic: 'Epic',
      ultra: 'Ultra',
      legendary: 'Legendary',
      exotic: 'Exotic',
      mythic: 'Mythic',
      god: 'God',
      ancient: 'Ancient',
      uniqueOwners: 'unique owners',
      account: 'Account',
      contract: 'Contract',
      allMarketTitle: 'All %collectionName%',
      listingsMarketTitle: '%collectionName% for Sale',
      bidsMarketTitle: 'Current Bids',
      ownedMarketTitle: '%collectionName% Owned',
      userMarketTitle: 'Owned Inscriptions',
      activityMarketTitle: 'Activity',
      oneOf: 'One of',
      isHeldInEscrowFor: 'is held in escrow for',
      isOwnedBy: 'is owned by',
      isForSaleFor: 'is for sale for',
      isNotSupported: 'is not supported by the marketplace.',
      isNotForSale: 'is not for sale.',
      noConsensus: 'does not have consensus with one or more indexers.',
      contactSupport: 'Contact support',
      resolveIssue: 'to resolve this issue.',
      viewOnEthscriptions: 'View on ethscriptions.com',
      mutate: 'Mutate',
      devolve: 'Devolve',
      haveThis: 'have this.',
      doesNotExist: "doesn't exist.",
      escrowRequirement: 'Your %singleName% must be held in escrow in order to be listed.',
      escrowRequirementSmall: 'While held in escrow, your Phunk will not show in your wallet on other apps/marketplaces.',
      blockCooldown: 'Block cooldown',
      notifSoldFor: 'Sold for',
      notifSubmitWallet: 'Please submit the transaction using your connected Ethereum wallet.',
      notifProcessing: 'Your transaction is being processed on the Ethereum network.',
      notifComplete: 'Your transaction is complete.',
      notifError: 'There was an error with your transaction.',
      newMessage: 'New message',
      transactionHistory: 'Transaction History',
      type: 'Type',
      to: 'To',
      amount: 'Amount',
      txn: 'Txn',
      escrow: 'Escrow',
      bidEntered: 'Bid Entered',
      offerWithdrawn: 'Offer Withdrawn',
      lock: 'Lock',
      unlock: 'Unlock',
      auctionStart: 'Auction Start',
    },
    es: {
      withdrawFunds: 'Retirar Fondos',
      disconnect: 'Desconectar',
      fartLeaderboard: 'Tabla de Farts',
      fartLeaderboardDescription: 'Los Farts representan tu actividad de compra en el ecosistema. Gana farts comprando items en el mercado, subastas y lotería.',
      farts: 'Farts',
      wallet: 'Wallet',
      buys: 'Compras',
      noResultsFound: 'No se encontraron resultados.',
      topFartHolder: '#1 dueño de Farts',
      curatedCollections: 'Colecciones Curadas',
      philipLottery: 'Lotería Philip V67',
      pro: 'Pro',
      auctionHouse: 'Casa de Subastas',
      phunkquidity: 'Phunkquidity',
      phunkSwap: 'Cambio Phunk',
      allOwners: 'Todos los Dueños',
      dystolabz: 'DystoLabz',
      adminPanel: 'Panel Admin',
      yourActivity: 'Tu Actividad',
      noRecentActivity: 'Sin actividad reciente.',
      back: 'Atrás',
      active: 'Activos',
      listings: 'Listados',
      languageAndFontControls: 'Controles de idioma y fuente',
      english: 'Ingles',
      spanish: 'Espanol',
      japanese: 'Japones',
      chinese: 'Chino',
      defaultFont: 'Fuente normal',
      blockscriptFont: 'Fuente Blockscript',
      highBlockscriptFont: 'Fuente High Blockscript',
      leaderboardImageAlt: 'QuantumPhunk 9986',
      recentActivity: 'Actividad Reciente',
      all: 'Todo',
      offered: 'Ofrecidos',
      sold: 'Vendidos',
      transferred: 'Transferidos',
      created: 'Creados',
      won: 'Ganados',
      auction: 'Subasta',
      bid: 'puja',
      mutated: 'Mutados',
      devolved: 'Devueltos',
      bought: 'Comprado',
      for: 'por',
      of: 'de',
      by: 'por',
      inLotteryBy: 'en lotería por',
      auctionWonBy: 'Subasta ganada por',
      auctionEndedNoBids: 'Subasta terminó sin pujas',
      auctionBidOf: 'Puja de subasta de',
      newBidOf: 'Nueva puja de',
      offeredFor: 'Ofrecido por',
      transferredTo: 'Transferido a',
      bridgedLockedBy: 'Bridge bloqueado por',
      bridgedUnlockedBy: 'Bridge desbloqueado por',
      escrowedBy: 'En escrow por',
      mutatedBy: 'Mutado por',
      devolvedBy: 'Devuelto por',
      onAuction: 'En subasta',
      viewMore: 'Ver Más',
      bids: 'Pujas',
      reserve: 'Reserva',
      winning: 'Ganando',
      current: 'Actual',
      timeRemaining: 'Tiempo restante',
      settled: 'Liquidada',
      connectAuction: 'Conecta tu wallet para usar esta subasta',
      waitingAuction: 'Esperando que inicie la primera subasta',
      auctionClosed: 'Esta subasta ya cerró',
      settling: 'Liquidando...',
      settle: 'Liquidar',
      pending: 'Pendiente...',
      placeBid: 'Pujar',
      txPending: 'Tu transacción está pendiente.',
      viewOnEtherscan: 'Ver en etherscan',
      bidHistory: 'Historial de pujas',
      noBids: 'Esta subasta no tiene pujas',
      viewAll: 'Ver todo',
      connect: 'Conectar',
      pointsMultiplier: 'multiplicador de farts',
      badInputTryAgain: 'Entrada inválida. Intenta otra vez',
      searchPlaceholder: 'Buscar: 0x, ens o Ethscription ID',
      searchHistory: 'Historial de búsqueda',
      clear: 'borrar',
      close: 'cerrar',
      go: 'Ir',
      from: 'de',
      viewMessage: 'Ver mensaje',
      version: 'Versión',
      marketplace: 'Mercado',
      points: 'Farts',
      lottery: 'Lotería',
      lottery2: 'Lotería 2',
      mutation: 'Mutación',
      riskDisclaimer: 'Al usar esta app, aceptas todos los riesgos asociados, incluida la pérdida de fondos. Los creadores de QuantumPhunks no son responsables por problemas o daños que puedan surgir por su uso.',
      bePhunky: 'Sé Phree. Sé Phunky. 👍',
      marketStatus: 'Estado del Mercado',
      provenanceHash: 'Hash de Procedencia',
      buy: 'Comprar',
      sell: 'Vender',
      sendToEscrow: 'Enviar a escrow',
      withdrawFromEscrow: 'Retirar de escrow',
      delist: 'Quitar venta',
      transfer: 'Transferir',
      connectItem: 'Conecta una wallet de Ethereum para interactuar con este item',
      attributes: 'Atributos',
      attribute: 'Atributo',
      loading: 'Cargando...',
      transferToAddress: 'Transferir a dirección',
      cancel: 'Cancelar',
      submit: 'Enviar',
      askingPrice: 'Precio pedido',
      listPrivately: 'Listar privado',
      offerToAddress: 'Ofrecer a dirección',
      offer: 'Ofrecer',
      escrowSaleNotice: 'Ofrecer tu item en venta lo enviará a nuestro contrato para quedar en escrow. Puedes retirarlo en cualquier momento.',
      royaltyNotice: 'Se aplica una regalía del 5% en cada venta.',
      sendToEscrowCaps: 'Enviar a Escrow',
      auctionHistory: 'Historial de subastas',
      currentBlock: 'Actual',
      indexer: 'Indexador',
      synced: 'sincronizado',
      blocksBehind: 'bloques atrasado',
      indexerLogs: 'Logs del indexador',
      initializingLogs: 'Iniciando logs',
      connectedWaitingLogs: 'Conectado - esperando logs',
      loaded: 'cargados',
      openingLiveFeed: 'Abriendo feed del indexador...',
      waitingNextLog: 'Conectado. Esperando el siguiente log.',
      noSettledAuctions: 'Aún no se ha liquidado ninguna subasta',
      connectWallet: 'Conectar Wallet',
      detected: 'Detectada',
      owned: 'En Propiedad',
      forSale: 'En Venta',
      showingOwned: 'Mostrando propios',
      showingLowestOffers: 'Mostrando ofertas de precio más bajo',
      viewAllLower: 'ver todo',
      lowestPricePrefix: 'El precio más bajo de',
      currentlyForSaleIs: 'actualmente en venta es',
      viewAllCollectionPrefix: 'Ver todos',
      secondsAgo: 's atrás',
      minutesAgo: 'm atrás',
      hoursAgo: 'h atrás',
      daysAgo: 'd atrás',
      overallStats: 'Estadisticas Generales',
      totalArtifacts: 'Artefactos Totales',
      uniqueTraitValues: 'Valores Unicos',
      uniqueTraitTypes: 'Tipos Unicos',
      totalOneOfOnes: 'Total Uno de Uno',
      owners: 'Duenos',
      allTypesAndAttributes: 'Todos los Tipos y Atributos de %type%',
      rock: 'Rock',
      phunk: 'Phunk',
      showing: 'Mostrando',
      sort: 'Ordenar',
      filterByAttribute: 'Filtrar por Atributo',
      select: 'Seleccionar',
      selected: 'seleccionados',
      list: 'Listar',
      withdraw: 'Retirar',
      totalCost: 'Costo total',
      buySelected: 'Comprar Seleccionados',
      comments: 'Comentarios',
      leaveComment: 'Deja un comentario...',
      addComment: 'Agregar comentario',
      noComments: 'Sin comentarios.',
      reply: 'respuesta',
      replies: 'respuestas',
      delete: 'borrar',
      clearFilters: 'Borrar Filtros',
      typesAndAttributes: 'Tipos y Atributos',
      fullCollection: 'Coleccion Completa',
      on: 'ON',
      off: 'OFF',
      attributeCount: 'Conteo de Atributos',
      numberOfAttributes: '# de Atributos',
      rarity: 'Rareza',
      examples: 'Ejemplos',
      value: 'valor',
      values: 'valores',
      oneOfOne: 'Uno de Uno',
      common: 'Comun',
      uncommon: 'Poco Comun',
      rare: 'Raro',
      elite: 'Elite',
      epic: 'Epico',
      ultra: 'Ultra',
      legendary: 'Legendario',
      exotic: 'Exotico',
      mythic: 'Mitico',
      god: 'Dios',
      ancient: 'Antiguo',
      uniqueOwners: 'duenos unicos',
      account: 'Cuenta',
      contract: 'Contrato',
      allMarketTitle: 'Todos los %collectionName%',
      listingsMarketTitle: '%collectionName% en Venta',
      bidsMarketTitle: 'Pujas Actuales',
      ownedMarketTitle: '%collectionName% en Propiedad',
      userMarketTitle: 'Inscripciones en Propiedad',
      activityMarketTitle: 'Actividad',
      oneOf: 'Uno de',
      isHeldInEscrowFor: 'esta en escrow para',
      isOwnedBy: 'es de',
      isForSaleFor: 'esta en venta por',
      isNotSupported: 'no es compatible con el mercado.',
      isNotForSale: 'no esta en venta.',
      noConsensus: 'no tiene consenso con uno o mas indexadores.',
      contactSupport: 'Contactar soporte',
      resolveIssue: 'para resolver este problema.',
      viewOnEthscriptions: 'Ver en ethscriptions.com',
      mutate: 'Mutar',
      devolve: 'Devolver',
      haveThis: 'tienen esto.',
      doesNotExist: 'no existe.',
      escrowRequirement: 'Tu %singleName% debe estar en escrow para poder listarse.',
      escrowRequirementSmall: 'Mientras esta en escrow, tu Phunk no aparecera en tu wallet en otras apps/mercados.',
      blockCooldown: 'Bloques de espera',
      notifSoldFor: 'Vendido por',
      notifSubmitWallet: 'Confirma la transacción en tu wallet de Ethereum conectada.',
      notifProcessing: 'Tu transacción se está procesando en la red Ethereum.',
      notifComplete: 'Tu transacción está completa.',
      notifError: 'Hubo un error con tu transacción.',
      newMessage: 'Nuevo mensaje',
      transactionHistory: 'Historial de Transacciones',
      type: 'Tipo',
      to: 'A',
      amount: 'Cantidad',
      txn: 'Txn',
      escrow: 'Escrow',
      bidEntered: 'Puja ingresada',
      bidWithdrawn: 'Puja retirada',
      offerWithdrawn: 'Oferta retirada',
      lock: 'Bloquear',
      unlock: 'Desbloquear',
      auctionStart: 'Inicio de subasta',
    },
    ja: {
      withdrawFunds: '資金を引き出す',
      disconnect: '切断',
      fartLeaderboard: 'Fart ランキング',
      fartLeaderboardDescription: 'Farts はエコシステム内の購入アクティビティを表します。マーケット、オークション、宝くじでアイテムを購入して farts を獲得できます。',
      farts: 'Farts',
      wallet: 'ウォレット',
      buys: '購入',
      noResultsFound: '結果がありません。',
      topFartHolder: '#1 Fart ホルダー',
      curatedCollections: '厳選コレクション',
      philipLottery: 'Philip 宝くじ V67',
      pro: 'Pro',
      auctionHouse: 'オークション',
      phunkquidity: 'Phunkquidity',
      phunkSwap: 'Phunk 交換',
      allOwners: '全オーナー',
      dystolabz: 'DystoLabz',
      adminPanel: '管理パネル',
      yourActivity: 'あなたの履歴',
      noRecentActivity: '最近の活動はありません。',
      back: '戻る',
      active: '出品中',
      listings: 'リスト',
      languageAndFontControls: '言語とフォント設定',
      english: '英語',
      spanish: 'スペイン語',
      japanese: '日本語',
      chinese: '中国語',
      defaultFont: '標準フォント',
      blockscriptFont: 'Blockscript フォント',
      highBlockscriptFont: 'High Blockscript フォント',
      leaderboardImageAlt: 'QuantumPhunk 9986',
      recentActivity: '最近のアクティビティ',
      all: 'すべて',
      offered: '出品',
      sold: '販売済み',
      transferred: '転送',
      created: '作成',
      won: '当選',
      auction: 'オークション',
      bid: '入札',
      mutated: '変異',
      devolved: '戻す',
      bought: '購入',
      for: '価格',
      of: 'の',
      by: 'by',
      inLotteryBy: '宝くじで獲得',
      auctionWonBy: 'オークション落札者',
      auctionEndedNoBids: 'オークション終了 - 入札なし',
      auctionBidOf: 'オークション入札',
      newBidOf: '新しい入札',
      bidWithdrawn: '入札取り消し',
      offeredFor: '出品価格',
      transferredTo: '転送先',
      bridgedLockedBy: 'ブリッジロック by',
      bridgedUnlockedBy: 'ブリッジ解除 by',
      escrowedBy: 'エスクロー by',
      mutatedBy: '変異 by',
      devolvedBy: '戻し by',
      onAuction: 'オークション中',
      viewMore: 'もっと見る',
      bids: '入札',
      reserve: 'リザーブ',
      winning: '落札',
      current: '現在',
      timeRemaining: '残り時間',
      settled: '決済済み',
      connectAuction: 'ウォレットを接続してオークションに参加',
      waitingAuction: '最初のオークション開始待ち',
      auctionClosed: 'このオークションは終了しました',
      settling: '決済中...',
      settle: '決済',
      pending: '保留中...',
      placeBid: '入札',
      txPending: 'トランザクション保留中です。',
      viewOnEtherscan: 'etherscanで見る',
      bidHistory: '入札履歴',
      noBids: 'このオークションには入札がありません',
      viewAll: 'すべて表示',
      connect: '接続',
      pointsMultiplier: 'Farts 倍率',
      badInputTryAgain: '入力エラー。再試行',
      searchPlaceholder: '検索: 0x、ens、Ethscription ID',
      searchHistory: '検索履歴',
      clear: 'クリア',
      close: '閉じる',
      go: 'Go',
      from: 'from',
      viewMessage: 'メッセージを見る',
      version: 'バージョン',
      marketplace: 'マーケット',
      points: 'Farts',
      lottery: '宝くじ',
      lottery2: '宝くじ 2',
      mutation: '変異',
      riskDisclaimer: 'このアプリを使用すると、資金損失を含むすべてのリスクを受け入れたことになります。QuantumPhunks の作成者は、使用により発生する問題や損害について責任を負いません。',
      bePhunky: 'Be Phree. Be Phunky. 👍',
      marketStatus: 'マーケット状態',
      provenanceHash: '来歴ハッシュ',
      buy: '購入',
      sell: '販売',
      sendToEscrow: 'エスクローへ送る',
      withdrawFromEscrow: 'エスクローから出す',
      delist: '出品取消',
      transfer: '転送',
      connectItem: 'このアイテムを操作するには Ethereum ウォレットを接続',
      attributes: '属性',
      attribute: '属性',
      loading: '読み込み中...',
      transferToAddress: '転送先アドレス',
      cancel: 'キャンセル',
      submit: '送信',
      askingPrice: '希望価格',
      listPrivately: '非公開出品',
      offerToAddress: 'オファー先アドレス',
      offer: 'オファー',
      escrowSaleNotice: 'アイテムを販売に出すと、エスクローとしてコントラクトに送られます。いつでも引き出せます。',
      royaltyNotice: '販売ごとに5%のロイヤルティが適用されます。',
      sendToEscrowCaps: 'エスクローへ送る',
      auctionHistory: 'オークション履歴',
      currentBlock: '現在',
      indexer: 'インデクサー',
      synced: '同期済み',
      blocksBehind: 'ブロック遅れ',
      indexerLogs: 'インデクサーログ',
      initializingLogs: 'ログ初期化中',
      connectedWaitingLogs: '接続済み - ログ待機中',
      loaded: '読み込み済み',
      openingLiveFeed: 'ライブフィードを開いています...',
      waitingNextLog: '接続済み。次のログを待機中。',
      noSettledAuctions: '決済済みオークションはまだありません',
      connectWallet: 'ウォレット接続',
      detected: '検出済み',
      owned: '所有',
      forSale: '販売中',
      showingOwned: '所有中を表示',
      showingLowestOffers: '最低価格オファーを表示',
      viewAllLower: 'すべて表示',
      lowestPricePrefix: '最低価格',
      currentlyForSaleIs: '現在の販売価格は',
      viewAllCollectionPrefix: 'すべて表示',
      secondsAgo: '秒前',
      minutesAgo: '分前',
      hoursAgo: '時間前',
      daysAgo: '日前',
      overallStats: '全体統計',
      totalArtifacts: '総アーティファクト',
      uniqueTraitValues: '固有属性値',
      uniqueTraitTypes: '固有属性タイプ',
      totalOneOfOnes: '1点物の合計',
      owners: 'オーナー',
      allTypesAndAttributes: 'すべての%type%タイプと属性',
      rock: 'Rock',
      phunk: 'Phunk',
      showing: '表示中',
      sort: '並び替え',
      filterByAttribute: '属性で絞り込み',
      select: '選択',
      selected: '選択済み',
      list: '出品',
      withdraw: '引き出す',
      totalCost: '合計',
      buySelected: '選択を購入',
      comments: 'コメント',
      leaveComment: 'コメントを書く...',
      addComment: 'コメント追加',
      noComments: 'コメントはありません。',
      reply: '返信',
      replies: '返信',
      delete: '削除',
      clearFilters: 'フィルター解除',
      typesAndAttributes: 'タイプと属性',
      fullCollection: '全コレクション',
      on: 'ON',
      off: 'OFF',
      attributeCount: '属性数',
      numberOfAttributes: '# 属性数',
      rarity: 'レア度',
      examples: '例',
      value: '値',
      values: '値',
      oneOfOne: '1点物',
      common: 'コモン',
      uncommon: 'アンコモン',
      rare: 'レア',
      elite: 'エリート',
      epic: 'エピック',
      ultra: 'ウルトラ',
      legendary: 'レジェンダリー',
      exotic: 'エキゾチック',
      mythic: 'ミシック',
      god: 'ゴッド',
      ancient: 'エンシェント',
      uniqueOwners: '固有オーナー',
      account: 'アカウント',
      contract: 'コントラクト',
      allMarketTitle: 'すべての%collectionName%',
      listingsMarketTitle: '販売中の%collectionName%',
      bidsMarketTitle: '現在の入札',
      ownedMarketTitle: '所有中の%collectionName%',
      userMarketTitle: '所有中のインスクリプション',
      activityMarketTitle: 'アクティビティ',
      oneOf: '全',
      isHeldInEscrowFor: 'は次のためにエスクロー中',
      isOwnedBy: 'の所有者',
      isForSaleFor: 'の販売価格',
      isNotSupported: 'はマーケットに対応していません。',
      isNotForSale: 'は販売中ではありません。',
      noConsensus: 'は1つ以上のインデクサーとコンセンサスがありません。',
      contactSupport: 'サポートに連絡',
      resolveIssue: 'して解決してください。',
      viewOnEthscriptions: 'ethscriptions.comで見る',
      mutate: '変異',
      devolve: '戻す',
      haveThis: 'がこの属性を持っています。',
      doesNotExist: 'は存在しません。',
      escrowRequirement: '%singleName%を出品するにはエスクローに入れる必要があります。',
      escrowRequirementSmall: 'エスクロー中、あなたのPhunkは他のアプリ/マーケットのウォレットに表示されません。',
      blockCooldown: 'ブロッククールダウン',
      notifSoldFor: '販売価格',
      notifSubmitWallet: '接続中の Ethereum ウォレットでトランザクションを送信してください。',
      notifProcessing: 'トランザクションは Ethereum ネットワークで処理中です。',
      notifComplete: 'トランザクションが完了しました。',
      notifError: 'トランザクションでエラーが発生しました。',
      newMessage: '新しいメッセージ',
      transactionHistory: '取引履歴',
      type: 'タイプ',
      to: '宛先',
      amount: '金額',
      txn: 'Txn',
      escrow: 'エスクロー',
      bidEntered: '入札入力',
      offerWithdrawn: 'オファー取消',
      lock: 'ロック',
      unlock: '解除',
      auctionStart: 'オークション開始',
    },
    zh: {
      withdrawFunds: '提取资金',
      disconnect: '断开连接',
      fartLeaderboard: 'Fart 排行榜',
      fartLeaderboardDescription: 'Farts 代表你在生态系统中的购买活动。通过在市场、拍卖和彩票中购买物品来赚取 farts。',
      farts: 'Farts',
      wallet: '钱包',
      buys: '购买',
      noResultsFound: '未找到结果。',
      topFartHolder: '#1 Fart 持有者',
      curatedCollections: '精选藏品',
      philipLottery: 'Philip 彩票 V67',
      pro: 'Pro',
      auctionHouse: '拍卖行',
      phunkquidity: 'Phunkquidity',
      phunkSwap: 'Phunk 交换',
      allOwners: '所有持有者',
      dystolabz: 'DystoLabz',
      adminPanel: '管理面板',
      yourActivity: '你的活动',
      noRecentActivity: '暂无近期活动。',
      back: '返回',
      active: '正在',
      listings: '上架',
      languageAndFontControls: '语言和字体设置',
      english: '英语',
      spanish: '西班牙语',
      japanese: '日语',
      chinese: '中文',
      defaultFont: '默认字体',
      blockscriptFont: 'Blockscript 字体',
      highBlockscriptFont: 'High Blockscript 字体',
      leaderboardImageAlt: 'QuantumPhunk 9986',
      recentActivity: '最近活动',
      all: '全部',
      offered: '已报价',
      sold: '已售',
      transferred: '已转移',
      created: '已创建',
      won: '赢得',
      auction: '拍卖',
      bid: '出价',
      mutated: '已变异',
      devolved: '已退化',
      bought: '买入',
      for: '价格',
      of: '的',
      by: '由',
      inLotteryBy: '彩票中奖者',
      auctionWonBy: '拍卖赢家',
      auctionEndedNoBids: '拍卖结束 - 无出价',
      auctionBidOf: '拍卖出价',
      newBidOf: '新出价',
      offeredFor: '报价',
      transferredTo: '转移给',
      bridgedLockedBy: '桥接锁定者',
      bridgedUnlockedBy: '桥接解锁者',
      escrowedBy: '托管者',
      mutatedBy: '变异者',
      devolvedBy: '退化者',
      onAuction: '拍卖中',
      viewMore: '查看更多',
      bids: '出价',
      reserve: '底价',
      winning: '获胜',
      current: '当前',
      timeRemaining: '剩余时间',
      settled: '已结算',
      connectAuction: '连接钱包以参与此拍卖',
      waitingAuction: '等待第一次拍卖开始',
      auctionClosed: '此拍卖已关闭',
      settling: '结算中...',
      settle: '结算',
      pending: '待处理...',
      placeBid: '出价',
      txPending: '你的交易正在待处理。',
      viewOnEtherscan: '在 etherscan 查看',
      bidHistory: '出价历史',
      noBids: '此拍卖没有出价',
      viewAll: '查看全部',
      connect: '连接',
      pointsMultiplier: 'Farts 倍数',
      badInputTryAgain: '输入错误，请重试',
      searchPlaceholder: '搜索: 0x、ens 或 Ethscription ID',
      searchHistory: '搜索历史',
      clear: '清除',
      close: '关闭',
      go: '前往',
      from: '来自',
      viewMessage: '查看消息',
      version: '版本',
      marketplace: '市场',
      points: 'Farts',
      lottery: '彩票',
      lottery2: '彩票 2',
      mutation: '变异',
      riskDisclaimer: '使用本应用即表示你接受所有相关风险，包括资金损失。QuantumPhunks 创建者不对使用过程中产生的问题或损害负责。',
      bePhunky: 'Be Phree. Be Phunky. 👍',
      marketStatus: '市场状态',
      provenanceHash: '来源哈希',
      buy: '购买',
      sell: '出售',
      sendToEscrow: '发送到托管',
      withdrawFromEscrow: '从托管取回',
      delist: '取消上架',
      transfer: '转移',
      connectItem: '连接 Ethereum 钱包以操作此项目',
      attributes: '属性',
      attribute: '属性',
      loading: '加载中...',
      transferToAddress: '转移到地址',
      cancel: '取消',
      submit: '提交',
      askingPrice: '要价',
      listPrivately: '私下上架',
      offerToAddress: '报价给地址',
      offer: '报价',
      escrowSaleNotice: '上架出售会把你的项目发送到我们的合约托管。你可以随时取回。',
      royaltyNotice: '每笔销售收取5%的版税。',
      sendToEscrowCaps: '发送到托管',
      auctionHistory: '拍卖历史',
      currentBlock: '当前',
      indexer: '索引器',
      synced: '已同步',
      blocksBehind: '区块落后',
      indexerLogs: '索引器日志',
      initializingLogs: '正在初始化日志',
      connectedWaitingLogs: '已连接 - 等待日志',
      loaded: '已加载',
      openingLiveFeed: '正在打开实时索引器...',
      waitingNextLog: '已连接。等待下一条日志。',
      noSettledAuctions: '还没有已结算的拍卖',
      connectWallet: '连接钱包',
      detected: '已检测',
      owned: '已拥有',
      forSale: '出售中',
      showingOwned: '显示已拥有',
      showingLowestOffers: '显示最低价报价',
      viewAllLower: '查看全部',
      lowestPricePrefix: '最低价格',
      currentlyForSaleIs: '当前出售价格为',
      viewAllCollectionPrefix: '查看全部',
      secondsAgo: '秒前',
      minutesAgo: '分钟前',
      hoursAgo: '小时前',
      daysAgo: '天前',
      overallStats: '总体统计',
      totalArtifacts: '总藏品',
      uniqueTraitValues: '唯一属性值',
      uniqueTraitTypes: '唯一属性类型',
      totalOneOfOnes: '总一对一',
      owners: '持有者',
      allTypesAndAttributes: '全部%type%类型和属性',
      rock: 'Rock',
      phunk: 'Phunk',
      showing: '显示',
      sort: '排序',
      filterByAttribute: '按属性筛选',
      select: '选择',
      selected: '已选择',
      list: '上架',
      withdraw: '取回',
      totalCost: '总成本',
      buySelected: '购买所选',
      comments: '评论',
      leaveComment: '留下评论...',
      addComment: '添加评论',
      noComments: '暂无评论。',
      reply: '回复',
      replies: '回复',
      delete: '删除',
      clearFilters: '清除筛选',
      typesAndAttributes: '类型和属性',
      fullCollection: '完整合集',
      on: 'ON',
      off: 'OFF',
      attributeCount: '属性数量',
      numberOfAttributes: '# 属性',
      rarity: '稀有度',
      examples: '示例',
      value: '值',
      values: '值',
      oneOfOne: '一对一',
      common: '普通',
      uncommon: '不常见',
      rare: '稀有',
      elite: '精英',
      epic: '史诗',
      ultra: '超稀有',
      legendary: '传奇',
      exotic: '异域',
      mythic: '神话',
      god: '神级',
      ancient: '远古',
      uniqueOwners: '唯一持有者',
      account: '账户',
      contract: '合约',
      allMarketTitle: '全部%collectionName%',
      listingsMarketTitle: '出售中的%collectionName%',
      bidsMarketTitle: '当前出价',
      ownedMarketTitle: '已拥有的%collectionName%',
      userMarketTitle: '已拥有的铭文',
      activityMarketTitle: '活动',
      oneOf: '共',
      isHeldInEscrowFor: '正在托管给',
      isOwnedBy: '拥有者为',
      isForSaleFor: '出售价格为',
      isNotSupported: '不受市场支持。',
      isNotForSale: '未出售。',
      noConsensus: '与一个或多个索引器没有达成共识。',
      contactSupport: '联系支持',
      resolveIssue: '以解决此问题。',
      viewOnEthscriptions: '在 ethscriptions.com 查看',
      mutate: '变异',
      devolve: '退化',
      haveThis: '拥有此属性。',
      doesNotExist: '不存在。',
      escrowRequirement: '你的%singleName%必须托管后才能上架。',
      escrowRequirementSmall: '托管期间，你的 Phunk 不会显示在其他应用/市场的钱包中。',
      blockCooldown: '区块冷却',
      notifSoldFor: '售出价格',
      notifSubmitWallet: '请使用已连接的 Ethereum 钱包提交交易。',
      notifProcessing: '你的交易正在 Ethereum 网络上处理。',
      notifComplete: '你的交易已完成。',
      notifError: '你的交易发生错误。',
      newMessage: '新消息',
      transactionHistory: '交易历史',
      type: '类型',
      to: '到',
      amount: '金额',
      txn: 'Txn',
      escrow: '托管',
      bidEntered: '已出价',
      bidWithdrawn: '出价已撤回',
      offerWithdrawn: '报价已撤回',
      lock: '锁定',
      unlock: '解锁',
      auctionStart: '拍卖开始',
    },
  };

  constructor(@Inject(DOCUMENT) private document: Document) {
    this.applyLanguage();
    this.applyFont();
  }

  t(key: string): string {
    return this.translations[this.currentLanguage()][key] || this.translations.en[key] || key;
  }

  setLanguage(language: MenuLanguage): void {
    this.currentLanguage.set(language);
    this.savePreference('qp-language', language);
    this.applyLanguage();
  }

  setFont(font: MenuFont): void {
    this.currentFont.set(font);
    this.savePreference('qp-font', font);
    this.applyFont();
  }

  private applyLanguage(): void {
    const htmlLang: Record<MenuLanguage, string> = {
      en: 'en',
      es: 'es-MX',
      ja: 'ja',
      zh: 'zh-CN',
    };

    this.document.documentElement.lang = htmlLang[this.currentLanguage()];
  }

  private applyFont(): void {
    if (this.currentFont() === 'default') {
      delete this.document.documentElement.dataset['phunkFont'];
      return;
    }

    this.document.documentElement.dataset['phunkFont'] = this.currentFont();
  }

  private loadLanguage(): MenuLanguage {
    const value = this.loadPreference('qp-language');
    return value === 'es' || value === 'ja' || value === 'zh' ? value : 'en';
  }

  private loadFont(): MenuFont {
    const font = this.loadPreference('qp-font');
    if (font === 'blockscript' || font === 'high-blockscript') return font;
    return 'default';
  }

  private loadPreference(key: string): string | null {
    try {
      return globalThis.localStorage?.getItem(key) ?? null;
    } catch {
      return null;
    }
  }

  private savePreference(key: string, value: string): void {
    try {
      globalThis.localStorage?.setItem(key, value);
    } catch {}
  }
}
