export const EtherPhunksEvolveABI = [
  {
    name: 'evolveFee',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'pairCount',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'pairIdOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'hashId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'feePaid',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'pairId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'registered',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'hashId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'depositor',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'hashId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'ogHashId',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'pairId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    name: 'quantumHashId',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'pairId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    name: 'isOg',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'hashId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
] as const;
