export const EtherPhunksEvolveABI = [
  {
    name: 'evolveFee',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'pairCount',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'pairIdOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'hashId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'feePaid',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'pairId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'registered',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'hashId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'depositor',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'hashId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'ogHashId',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'pairId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    name: 'quantumHashId',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'pairId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    name: 'isOg',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'hashId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'owner',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'paused',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  { name: 'pause', type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { name: 'unpause', type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  {
    name: 'setFee',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_fee', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'registerPairs',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_ogHashIds', type: 'bytes32[]' },
      { name: '_quantumHashIds', type: 'bytes32[]' },
    ],
    outputs: [],
  },
  { name: 'withdrawETH', type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  {
    name: 'withdrawEthscription',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'hashId', type: 'bytes32' },
      { name: 'to', type: 'address' },
    ],
    outputs: [],
  },
  {
    name: 'transferOwnership',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'newOwner', type: 'address' }],
    outputs: [],
  },
] as const;
